//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.07 at 03:02:37 PM CEST 
//


package fr.liglab.adele.rondo.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Application complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Application">
 *   &lt;complexContent>
 *     &lt;extension base="{fr.liglab.adele.rondo.core}Element">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="import" type="{fr.liglab.adele.rondo.application}Import"/>
 *         &lt;element name="binding" type="{fr.liglab.adele.rondo.application}Binding"/>
 *         &lt;element name="fragment" type="{fr.liglab.adele.rondo.application}ApplicationFragment"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Application", propOrder = {
    "importOrBindingOrFragment"
})
public class Application
    extends Element
{

    @XmlElements({
        @XmlElement(name = "binding", type = Binding.class),
        @XmlElement(name = "import", type = Import.class),
        @XmlElement(name = "fragment", type = ApplicationFragment.class)
    })
    protected List<Object> importOrBindingOrFragment;

    /**
     * Gets the value of the importOrBindingOrFragment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the importOrBindingOrFragment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImportOrBindingOrFragment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Binding }
     * {@link Import }
     * {@link ApplicationFragment }
     * 
     * 
     */
    public List<Object> getImportOrBindingOrFragment() {
        if (importOrBindingOrFragment == null) {
            importOrBindingOrFragment = new ArrayList<Object>();
        }
        return this.importOrBindingOrFragment;
    }

}
