//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.07 at 03:02:37 PM CEST 
//


package fr.liglab.adele.rondo.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Component complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Component">
 *   &lt;complexContent>
 *     &lt;extension base="{fr.liglab.adele.rondo.core}Element">
 *       &lt;sequence>
 *         &lt;element name="policy" type="{fr.liglab.adele.rondo.core}PolicyConfiguration"/>
 *         &lt;element name="configuation" type="{fr.liglab.adele.rondo.application}Configuration"/>
 *       &lt;/sequence>
 *       &lt;attribute name="implementationFilter" type="{fr.liglab.adele.rondo.core}Filter" />
 *       &lt;attribute name="specification" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="implementation" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Component", propOrder = {
    "policy",
    "configuation"
})
public class Component
    extends Element
{

    @XmlElement(required = true)
    protected PolicyConfiguration policy;
    @XmlElement(required = true)
    protected Configuration configuation;
    @XmlAttribute
    protected String implementationFilter;
    @XmlAttribute
    @XmlSchemaType(name = "anyURI")
    protected String specification;
    @XmlAttribute
    @XmlSchemaType(name = "anyURI")
    protected String implementation;

    /**
     * Gets the value of the policy property.
     * 
     * @return
     *     possible object is
     *     {@link PolicyConfiguration }
     *     
     */
    public PolicyConfiguration getPolicy() {
        return policy;
    }

    /**
     * Sets the value of the policy property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolicyConfiguration }
     *     
     */
    public void setPolicy(PolicyConfiguration value) {
        this.policy = value;
    }

    /**
     * Gets the value of the configuation property.
     * 
     * @return
     *     possible object is
     *     {@link Configuration }
     *     
     */
    public Configuration getConfiguation() {
        return configuation;
    }

    /**
     * Sets the value of the configuation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Configuration }
     *     
     */
    public void setConfiguation(Configuration value) {
        this.configuation = value;
    }

    /**
     * Gets the value of the implementationFilter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImplementationFilter() {
        return implementationFilter;
    }

    /**
     * Sets the value of the implementationFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImplementationFilter(String value) {
        this.implementationFilter = value;
    }

    /**
     * Gets the value of the specification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecification() {
        return specification;
    }

    /**
     * Sets the value of the specification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecification(String value) {
        this.specification = value;
    }

    /**
     * Gets the value of the implementation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImplementation() {
        return implementation;
    }

    /**
     * Sets the value of the implementation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImplementation(String value) {
        this.implementation = value;
    }

}
