//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.11 at 04:38:36 PM CEST 
//


package fr.liglab.adele.rondo.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Configuration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Configuration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="provides" type="{fr.liglab.adele.rondo.application}ConfigurationServiceProviding"/>
 *         &lt;element name="dependency" type="{fr.liglab.adele.rondo.application}ConfigurationServiceDependency"/>
 *         &lt;element name="dataPublish" type="{fr.liglab.adele.rondo.application}ConfigurationDataPublishing"/>
 *         &lt;element name="dataConsume" type="{fr.liglab.adele.rondo.application}ConfigurationDataConsuming"/>
 *         &lt;element name="property" type="{fr.liglab.adele.rondo.application}ConfigurationProperty"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Configuration", propOrder = {
    "providesOrDependencyOrDataPublish"
})
public class Configuration {

    @XmlElements({
        @XmlElement(name = "property", type = ConfigurationProperty.class),
        @XmlElement(name = "dependency", type = ConfigurationServiceDependency.class),
        @XmlElement(name = "dataPublish", type = ConfigurationDataPublishing.class),
        @XmlElement(name = "provides", type = ConfigurationServiceProviding.class),
        @XmlElement(name = "dataConsume", type = ConfigurationDataConsuming.class)
    })
    protected List<Object> providesOrDependencyOrDataPublish;

    /**
     * Gets the value of the providesOrDependencyOrDataPublish property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the providesOrDependencyOrDataPublish property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProvidesOrDependencyOrDataPublish().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConfigurationProperty }
     * {@link ConfigurationServiceDependency }
     * {@link ConfigurationDataPublishing }
     * {@link ConfigurationServiceProviding }
     * {@link ConfigurationDataConsuming }
     * 
     * 
     */
    public List<Object> getProvidesOrDependencyOrDataPublish() {
        if (providesOrDependencyOrDataPublish == null) {
            providesOrDependencyOrDataPublish = new ArrayList<Object>();
        }
        return this.providesOrDependencyOrDataPublish;
    }

}
