//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.11 at 04:38:36 PM CEST 
//


package fr.liglab.adele.rondo.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Import complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Import">
 *   &lt;complexContent>
 *     &lt;extension base="{fr.liglab.adele.rondo.core}Element">
 *       &lt;sequence>
 *         &lt;element name="policy" type="{fr.liglab.adele.rondo.core}PolicyConfiguration"/>
 *         &lt;element name="configuration" type="{fr.liglab.adele.rondo.application}Configuration"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Import", propOrder = {
    "policy",
    "configuration"
})
public class Import
    extends Element
{

    @XmlElement(required = true)
    protected PolicyConfiguration policy;
    @XmlElement(required = true)
    protected Configuration configuration;

    /**
     * Gets the value of the policy property.
     * 
     * @return
     *     possible object is
     *     {@link PolicyConfiguration }
     *     
     */
    public PolicyConfiguration getPolicy() {
        return policy;
    }

    /**
     * Sets the value of the policy property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolicyConfiguration }
     *     
     */
    public void setPolicy(PolicyConfiguration value) {
        this.policy = value;
    }

    /**
     * Gets the value of the configuration property.
     * 
     * @return
     *     possible object is
     *     {@link Configuration }
     *     
     */
    public Configuration getConfiguration() {
        return configuration;
    }

    /**
     * Sets the value of the configuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Configuration }
     *     
     */
    public void setConfiguration(Configuration value) {
        this.configuration = value;
    }

}
