//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.07 at 03:02:37 PM CEST 
//


package fr.liglab.adele.rondo.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fr.liglab.adele.rondo.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Property_QNAME = new QName("fr.liglab.adele.rondo.core", "Property");
    private final static QName _Component_QNAME = new QName("fr.liglab.adele.rondo.application", "component");
    private final static QName _PolicyConfiguration_QNAME = new QName("fr.liglab.adele.rondo.core", "PolicyConfiguration");
    private final static QName _Import_QNAME = new QName("fr.liglab.adele.rondo.application", "import");
    private final static QName _ConfigurationProperty_QNAME = new QName("fr.liglab.adele.rondo.application", "ConfigurationProperty");
    private final static QName _Binding_QNAME = new QName("fr.liglab.adele.rondo.application", "binding");
    private final static QName _ApplicationFragment_QNAME = new QName("fr.liglab.adele.rondo.application", "applicationFragment");
    private final static QName _ConfigurationDataConsuming_QNAME = new QName("fr.liglab.adele.rondo.application", "ConfigurationDataConsuming");
    private final static QName _Configuration_QNAME = new QName("fr.liglab.adele.rondo.application", "configuration");
    private final static QName _Application_QNAME = new QName("fr.liglab.adele.rondo.application", "application");
    private final static QName _PropertyValue_QNAME = new QName("fr.liglab.adele.rondo.core", "PropertyValue");
    private final static QName _Element_QNAME = new QName("fr.liglab.adele.rondo.core", "Element");
    private final static QName _ConfigurationDataPublishing_QNAME = new QName("fr.liglab.adele.rondo.application", "ConfigurationDataPublishing");
    private final static QName _ConfigurationServiceProviding_QNAME = new QName("fr.liglab.adele.rondo.application", "ConfigurationServiceProviding");
    private final static QName _Policy_QNAME = new QName("fr.liglab.adele.rondo.core", "Policy");
    private final static QName _ConfigurationServiceDependency_QNAME = new QName("fr.liglab.adele.rondo.application", "ConfigurationServiceDependency");
    private final static QName _Rondo_QNAME = new QName("fr.liglab.adele.rondo.application", "rondo");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fr.liglab.adele.rondo.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Application }
     * 
     */
    public Application createApplication() {
        return new Application();
    }

    /**
     * Create an instance of {@link ApplicationFragment }
     * 
     */
    public ApplicationFragment createApplicationFragment() {
        return new ApplicationFragment();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link Policy }
     * 
     */
    public Policy createPolicy() {
        return new Policy();
    }

    /**
     * Create an instance of {@link Rondo }
     * 
     */
    public Rondo createRondo() {
        return new Rondo();
    }

    /**
     * Create an instance of {@link Configuration }
     * 
     */
    public Configuration createConfiguration() {
        return new Configuration();
    }

    /**
     * Create an instance of {@link ConfigurationServiceDependency }
     * 
     */
    public ConfigurationServiceDependency createConfigurationServiceDependency() {
        return new ConfigurationServiceDependency();
    }

    /**
     * Create an instance of {@link PolicyConfiguration }
     * 
     */
    public PolicyConfiguration createPolicyConfiguration() {
        return new PolicyConfiguration();
    }

    /**
     * Create an instance of {@link PropertyValue }
     * 
     */
    public PropertyValue createPropertyValue() {
        return new PropertyValue();
    }

    /**
     * Create an instance of {@link ConfigurationProperty }
     * 
     */
    public ConfigurationProperty createConfigurationProperty() {
        return new ConfigurationProperty();
    }

    /**
     * Create an instance of {@link ConfigurationServiceProviding }
     * 
     */
    public ConfigurationServiceProviding createConfigurationServiceProviding() {
        return new ConfigurationServiceProviding();
    }

    /**
     * Create an instance of {@link Component }
     * 
     */
    public Component createComponent() {
        return new Component();
    }

    /**
     * Create an instance of {@link ConfigurationDataConsuming }
     * 
     */
    public ConfigurationDataConsuming createConfigurationDataConsuming() {
        return new ConfigurationDataConsuming();
    }

    /**
     * Create an instance of {@link Binding }
     * 
     */
    public Binding createBinding() {
        return new Binding();
    }

    /**
     * Create an instance of {@link ConfigurationDataPublishing }
     * 
     */
    public ConfigurationDataPublishing createConfigurationDataPublishing() {
        return new ConfigurationDataPublishing();
    }

    /**
     * Create an instance of {@link Import }
     * 
     */
    public Import createImport() {
        return new Import();
    }

    /**
     * Create an instance of {@link ConfigurationElement }
     * 
     */
    public ConfigurationElement createConfigurationElement() {
        return new ConfigurationElement();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Property }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "fr.liglab.adele.rondo.core", name = "Property")
    public JAXBElement<Property> createProperty(Property value) {
        return new JAXBElement<Property>(_Property_QNAME, Property.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Component }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "fr.liglab.adele.rondo.application", name = "component")
    public JAXBElement<Component> createComponent(Component value) {
        return new JAXBElement<Component>(_Component_QNAME, Component.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PolicyConfiguration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "fr.liglab.adele.rondo.core", name = "PolicyConfiguration")
    public JAXBElement<PolicyConfiguration> createPolicyConfiguration(PolicyConfiguration value) {
        return new JAXBElement<PolicyConfiguration>(_PolicyConfiguration_QNAME, PolicyConfiguration.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Import }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "fr.liglab.adele.rondo.application", name = "import")
    public JAXBElement<Import> createImport(Import value) {
        return new JAXBElement<Import>(_Import_QNAME, Import.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConfigurationProperty }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "fr.liglab.adele.rondo.application", name = "ConfigurationProperty")
    public JAXBElement<ConfigurationProperty> createConfigurationProperty(ConfigurationProperty value) {
        return new JAXBElement<ConfigurationProperty>(_ConfigurationProperty_QNAME, ConfigurationProperty.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Binding }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "fr.liglab.adele.rondo.application", name = "binding")
    public JAXBElement<Binding> createBinding(Binding value) {
        return new JAXBElement<Binding>(_Binding_QNAME, Binding.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApplicationFragment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "fr.liglab.adele.rondo.application", name = "applicationFragment")
    public JAXBElement<ApplicationFragment> createApplicationFragment(ApplicationFragment value) {
        return new JAXBElement<ApplicationFragment>(_ApplicationFragment_QNAME, ApplicationFragment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConfigurationDataConsuming }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "fr.liglab.adele.rondo.application", name = "ConfigurationDataConsuming")
    public JAXBElement<ConfigurationDataConsuming> createConfigurationDataConsuming(ConfigurationDataConsuming value) {
        return new JAXBElement<ConfigurationDataConsuming>(_ConfigurationDataConsuming_QNAME, ConfigurationDataConsuming.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Configuration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "fr.liglab.adele.rondo.application", name = "configuration")
    public JAXBElement<Configuration> createConfiguration(Configuration value) {
        return new JAXBElement<Configuration>(_Configuration_QNAME, Configuration.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Application }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "fr.liglab.adele.rondo.application", name = "application")
    public JAXBElement<Application> createApplication(Application value) {
        return new JAXBElement<Application>(_Application_QNAME, Application.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PropertyValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "fr.liglab.adele.rondo.core", name = "PropertyValue")
    public JAXBElement<PropertyValue> createPropertyValue(PropertyValue value) {
        return new JAXBElement<PropertyValue>(_PropertyValue_QNAME, PropertyValue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Element }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "fr.liglab.adele.rondo.core", name = "Element")
    public JAXBElement<Element> createElement(Element value) {
        return new JAXBElement<Element>(_Element_QNAME, Element.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConfigurationDataPublishing }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "fr.liglab.adele.rondo.application", name = "ConfigurationDataPublishing")
    public JAXBElement<ConfigurationDataPublishing> createConfigurationDataPublishing(ConfigurationDataPublishing value) {
        return new JAXBElement<ConfigurationDataPublishing>(_ConfigurationDataPublishing_QNAME, ConfigurationDataPublishing.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConfigurationServiceProviding }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "fr.liglab.adele.rondo.application", name = "ConfigurationServiceProviding")
    public JAXBElement<ConfigurationServiceProviding> createConfigurationServiceProviding(ConfigurationServiceProviding value) {
        return new JAXBElement<ConfigurationServiceProviding>(_ConfigurationServiceProviding_QNAME, ConfigurationServiceProviding.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Policy }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "fr.liglab.adele.rondo.core", name = "Policy")
    public JAXBElement<Policy> createPolicy(Policy value) {
        return new JAXBElement<Policy>(_Policy_QNAME, Policy.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConfigurationServiceDependency }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "fr.liglab.adele.rondo.application", name = "ConfigurationServiceDependency")
    public JAXBElement<ConfigurationServiceDependency> createConfigurationServiceDependency(ConfigurationServiceDependency value) {
        return new JAXBElement<ConfigurationServiceDependency>(_ConfigurationServiceDependency_QNAME, ConfigurationServiceDependency.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Rondo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "fr.liglab.adele.rondo.application", name = "rondo")
    public JAXBElement<Rondo> createRondo(Rondo value) {
        return new JAXBElement<Rondo>(_Rondo_QNAME, Rondo.class, null, value);
    }

}
