//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.07 at 05:44:51 PM CEST 
//


package fr.liglab.adele.rondo.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fr.liglab.adele.rondo.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Property_QNAME = new QName("fr.liglab.adele.rondo.core", "Property");
    private final static QName _PropertyValue_QNAME = new QName("fr.liglab.adele.rondo.core", "PropertyValue");
    private final static QName _Element_QNAME = new QName("fr.liglab.adele.rondo.core", "Element");
    private final static QName _PolicyConfiguration_QNAME = new QName("fr.liglab.adele.rondo.core", "PolicyConfiguration");
    private final static QName _Policy_QNAME = new QName("fr.liglab.adele.rondo.core", "Policy");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fr.liglab.adele.rondo.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Component }
     * 
     */
    public Component createComponent() {
        return new Component();
    }

    /**
     * Create an instance of {@link PolicyConfiguration }
     * 
     */
    public PolicyConfiguration createPolicyConfiguration() {
        return new PolicyConfiguration();
    }

    /**
     * Create an instance of {@link ConfigurationDataPublishing }
     * 
     */
    public ConfigurationDataPublishing createConfigurationDataPublishing() {
        return new ConfigurationDataPublishing();
    }

    /**
     * Create an instance of {@link PropertyValue }
     * 
     */
    public PropertyValue createPropertyValue() {
        return new PropertyValue();
    }

    /**
     * Create an instance of {@link ConfigurationServiceProviding }
     * 
     */
    public ConfigurationServiceProviding createConfigurationServiceProviding() {
        return new ConfigurationServiceProviding();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link ApplicationFragment }
     * 
     */
    public ApplicationFragment createApplicationFragment() {
        return new ApplicationFragment();
    }

    /**
     * Create an instance of {@link Policy }
     * 
     */
    public Policy createPolicy() {
        return new Policy();
    }

    /**
     * Create an instance of {@link Configuration }
     * 
     */
    public Configuration createConfiguration() {
        return new Configuration();
    }

    /**
     * Create an instance of {@link ConfigurationServiceDependency }
     * 
     */
    public ConfigurationServiceDependency createConfigurationServiceDependency() {
        return new ConfigurationServiceDependency();
    }

    /**
     * Create an instance of {@link Binding }
     * 
     */
    public Binding createBinding() {
        return new Binding();
    }

    /**
     * Create an instance of {@link ConfigurationDataConsuming }
     * 
     */
    public ConfigurationDataConsuming createConfigurationDataConsuming() {
        return new ConfigurationDataConsuming();
    }

    /**
     * Create an instance of {@link Import }
     * 
     */
    public Import createImport() {
        return new Import();
    }

    /**
     * Create an instance of {@link Application }
     * 
     */
    public Application createApplication() {
        return new Application();
    }

    /**
     * Create an instance of {@link Rondo }
     * 
     */
    public Rondo createRondo() {
        return new Rondo();
    }

    /**
     * Create an instance of {@link ConfigurationProperty }
     * 
     */
    public ConfigurationProperty createConfigurationProperty() {
        return new ConfigurationProperty();
    }

    /**
     * Create an instance of {@link ConfigurationElement }
     * 
     */
    public ConfigurationElement createConfigurationElement() {
        return new ConfigurationElement();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Property }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "fr.liglab.adele.rondo.core", name = "Property")
    public JAXBElement<Property> createProperty(Property value) {
        return new JAXBElement<Property>(_Property_QNAME, Property.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PropertyValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "fr.liglab.adele.rondo.core", name = "PropertyValue")
    public JAXBElement<PropertyValue> createPropertyValue(PropertyValue value) {
        return new JAXBElement<PropertyValue>(_PropertyValue_QNAME, PropertyValue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Element }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "fr.liglab.adele.rondo.core", name = "Element")
    public JAXBElement<Element> createElement(Element value) {
        return new JAXBElement<Element>(_Element_QNAME, Element.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PolicyConfiguration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "fr.liglab.adele.rondo.core", name = "PolicyConfiguration")
    public JAXBElement<PolicyConfiguration> createPolicyConfiguration(PolicyConfiguration value) {
        return new JAXBElement<PolicyConfiguration>(_PolicyConfiguration_QNAME, PolicyConfiguration.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Policy }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "fr.liglab.adele.rondo.core", name = "Policy")
    public JAXBElement<Policy> createPolicy(Policy value) {
        return new JAXBElement<Policy>(_Policy_QNAME, Policy.class, null, value);
    }

}
