//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.11 at 04:38:36 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "fr.liglab.adele.rondo.application")
package fr.liglab.adele.rondo.model;
